
all_headers = [["CT Trafo Primary Current AVG", "CT Trafo Secondary Current AVG", "Choke RC Snubber Capacitor Current AVG", "Choke RC Snubber Resistance Current AVG", "Choke RC Snubber Par Res Current AVG", "RCD Clamp Capacitor Current AVG", "RCD Clamp Resistance Current AVG", "Freewheeler Blocking Cap Current AVG", "Freewheeler Resistor Current AVG", "Freewheeler Impedance Cap Current AVG", "Damping Resistor Current AVG", "LV Current Sensor Current AVG", "HV X-Caps 1 Current AVG", "HV X-Caps 2 Current AVG", "HV Current Sensor Current AVG", "Blocking Capacitor Current AVG", "Transformer Snubber Cap Current AVG", "Transformer Snubber Res Current AVG", "MOSFET RC Snubber Cap Current AVG", "MOSFET RC Snubber Res Current AVG", "HV Y-Caps Current AVG", "LV FullBridge Snubber Cap Current AVG", "LV FullBridge Snubber Res Current AVG", "HV Snubber Caps Current AVG", "Output Ceramic Capacitors Current AVG", "Output Electrolytic Capacitors Current AVG", "Output Y-Cap Current AVG", "HV Voltage Sensor Current AVG", "HV CMC Choke Current AVG", "LV Filter X-Cap 1 Current AVG", "LV Filter X-Cap 2 Current AVG", "LV Filter Elko-Cap Current AVG", "LV Filter Y-Cap Current AVG", "LV Filter DMC Current AVG", "LV Filter CMC Current AVG", "LV Filter Output Current RbPlus AVG", "LV Filter Output Current RbMinus AVG", "RCD Clamp Transistor Current AVG", "RCD Clamp Bodydiode Current AVG", "LV Rectifiers Current 1 AVG", "LV Rectifiers Current 2 AVG", "DC Choke Current AVG", "Freewheeler Switch Current 1 AVG", "Freewheeler Switch Current 2 AVG", "Short Circuit Current 1 AVG", "Short Circuit Current 2 AVG", "HV Left-Leg HS Current 1 AVG", "HV Left-Leg HS Current 2 AVG", "HV Right-Leg HS Current 1 AVG", "HV Right-Leg HS Current 2 AVG", "Transformer Primary Current AVG", "Transformer Secondary Current AVG", "Transformer Magnetizing Current AVG", "HV Left-Leg ON Current AVG", "HV Left-Leg OFF Current AVG", "HV Left-Leg Max Current1 AVG", "HV Left-Leg Max Current2 AVG", "HV Right-Leg ON Current AVG", "HV Right-Leg OFF Current AVG", "HV Right-Leg Max Current1 AVG", "HV Right-Leg Max Current2 AVG", "Pack Current AVG", "Relay Current Main AVG", "Relay Current DCDC AVG", "DC Link Current AVG", "KL30 Current AVG", "ENBN DCDC Current AVG", "ENBN Battery Current AVG", "LV Filter Input Current AVG", "LV Filter Output Current AVG", "CISPR Input Current AVG", "CISPR Output Current AVG", "Load L_F Current AVG", "Load L_B Current AVG", "CTRL Current AVG", "PECU Current AVG", "Rbox Current AVG"],
               ["CT Trafo Primary Voltage AVG", "CT Trafo Secondary Voltage AVG", "Choke RC Snubber Voltage 1 AVG", "Choke RC Snubber Voltage 2 AVG", "Choke RC Snubber Voltage 3 AVG", "RCD Clamp Capacitor Voltage AVG", "RCD Clamp Resistance Voltage AVG", "Freewheeler Blocking Cap Voltage AVG", "Freewheeler Resistor Voltage AVG", "Freewheeler Impedance Cap Voltage AVG", "Damping Resistor Voltage AVG", "LV Current Sensor Voltage AVG", "HV X-Caps 1 Voltage AVG", "HV X-Caps 2 Voltage AVG", "HV Current Sensor Voltage AVG", "Blocking Capacitor Voltage AVG", "Transformer Snubber Voltage 1 AVG", "Transformer Snubber Voltage 2 AVG", "MOSFET RC Snubber Voltage 1 AVG", "MOSFET RC Snubber Voltage 2 AVG", "HV Y-Caps Voltage AVG", "LV FullBridge Snubber Voltage 1 AVG", "LV FullBridge Snubber Voltage 2 AVG", "HV Snubber Caps Voltage AVG", "Output Ceramic Capacitors Voltage AVG", "Output Electrolytic Capacitors Voltage AVG", "Output Y-Cap Voltage AVG", "HV Voltage Sensor Voltage AVG", "HV CMC Choke Voltage AVG", "LV Filter X-Cap 1 Voltage AVG", "LV Filter X-Cap 2 Voltage AVG", "LV Filter Elko-Cap Voltage AVG", "LV Filter Y-Cap Voltage AVG", "LV Filter DMC Voltage AVG", "LV Filter CMC Voltage AVG", "LV Filter Output Voltage 1 AVG", "LV Filter Output Voltage 2 AVG", "RCD Clamp Transistor Voltage AVG", "RCD Clamp Bodydiode Voltage AVG", "LV Rectifiers Voltage 1 AVG", "LV Rectifiers Voltage 2 AVG", "DC Choke Voltage AVG", "Freewheeler Switch Voltage 1 AVG", "Freewheeler Switch Voltage 2 AVG", "Short Circuit Voltage 1 AVG", "Short Circuit Voltage 2 AVG", "HV Left-Leg HS Voltage 1 AVG", "HV Left-Leg HS Voltage 2 AVG", "HV Right-Leg HS Voltage 1 AVG", "HV Right-Leg HS Voltage 2 AVG", "Transformer Primary Voltage AVG", "Transformer Secondary Voltage AVG", "Transformer Flux AVG", "Pack Voltage AVG", "Relay Voltage Main AVG", "Relay Voltage DCDC AVG", "DC Link Voltage AVG", "KL30 Voltage AVG", "ENBN DCDC Voltage AVG", "ENBN Battery Voltage AVG", "LV Filter Input Voltage AVG", "LV Filter Output Voltage 3 AVG", "CISPR Input Voltage AVG", "CISPR Output Voltage AVG", "Load L_F Voltage AVG", "Load L_B Voltage AVG", "CTRL Voltage AVG", "PECU Voltage AVG", "Rbox Voltage AVG"],
               ["PWM Modulator Carrier Waveforms 1", "PWM Modulator Carrier Waveforms 2", "PWM Modulator Primary Modulator Duty Cycle", "PWM Modulator Secondary Modulator Duty Cycle", "PWM Modulator Primary PWM Outputs S1", "PWM Modulator Primary PWM Outputs S2", "PWM Modulator Primary PWM Outputs S3", "PWM Modulator Primary PWM Outputs S4", "PWM Modulator Secondary PWM Outputs S5", "PWM Modulator Secondary PWM Outputs S6", "PWM Modulator Secondary PWM Outputs S7", "PWM Modulator Secondary PWM Outputs S8", "PWM Modulator Auxiliary PWM Outputs Sac", "PWM Modulator Auxiliary PWM Outputs Sfw", "PWM Modulator Auxiliary PWM Outputs Ssc", "PWM Modulator Auxiliary PWM Outputs Sdis", "Measured Output Ceramic Capacitors Voltage", "Measured LV Filter Output Voltage", "Measured ADCs Sampled Signals 1", "Measured ADCs Analog Signals 1", "Measured ADCs ADC Signals 1", "Measured HW Protection Comparator Signals 1", "Measured PSFB LV Current Sensor Current", "Measured ADCs Sampled Signals 2", "Measured ADCs Analog Signals 2", "Measured ADCs ADC Signals 2", "Measured HW Protection Comparator Signals 2", "Measured HV Filter Voltages 1", "Measured HV Filter Voltages 2", "Measured ADCs Sampled Signals 3", "Measured ADCs Analog Signals 3", "Measured ADCs ADC Signals 3", "Measured HW Protection Comparator Signals 3", "Measured HV Current Sensor Current", "Measured ADCs Sampled Signals 4", "Measured ADCs ADC Signals 4", "Measured CT Current Sensor Current", "Measured ADCs Sampled Signals 5", "Measured ADCs ADC Signals 5", "Measured ADCs Sensors Digital Values Vo", "Measured ADCs Sensors Digital Values Io", "Measured ADCs Sensors Digital Values Vin", "Measured ADCs Sensors Digital Values Iin", "Measured ADCs Sensors Digital Values CT", "Measured ADCs Digital Reference", "ADCs ADC Pin Voltages 1", "ADCs S-and-H Voltages 1", "ADCs Sampled Voltages 1", "ADCs ADC Pin Voltages 2", "ADCs S-and-H Voltages 2", "ADCs Sampled Voltages 2", "ADCs ADC Pin Voltages 3", "ADCs S-and-H Voltages 3", "ADCs Sampled Voltages 3", "ADCs ADC Pin Voltages 4", "ADCs S-and-H Voltages 4", "ADCs Sampled Voltages 4", "ADCs ADC Pin Voltages 5", "ADCs S-and-H Voltages 5", "ADCs Sampled Voltages 5", "ADCs Charging Currents 1", "ADCs Charging Currents 2", "ADCs Charging Currents 3", "ADCs Charging Currents 4", "ADCs Charging Currents 5", "ADCs Charging Currents 6", "ADCs Charging Currents 7", "ADCs Charging Currents 8", "ADCs Charging Currents 9", "ADCs Charging Currents 10", "ADCs Sampling Triggers 1", "ADCs Sampling Triggers 2", "ADCs Sampling Triggers 3", "ADCs Sampling Triggers 4", "ADCs Sampling Triggers 5", "PSFB Output Ceramic Capacitors Voltage", "LV Filter Input Voltage Sampling", "LV Filter Output Voltage Sampling", "LV Current Sensor Current Sampling", "HV Filter X-Caps Voltages 1 Sampling", "HV Filter X-Caps Voltages 2 Sampling", "HV Current Sensor Current Sampling", "CT Current Sensor Current Sampling", "PWM Modulator Primary PWM Outputs 1", "PWM Modulator Primary PWM Outputs 2", "PWM Modulator Primary PWM Outputs 3", "PWM Modulator Primary PWM Outputs 4", "PWM Modulator Secondary PWM Outputs 1", "PWM Modulator Secondary PWM Outputs 2", "PWM Modulator Secondary PWM Outputs 3", "PWM Modulator Secondary PWM Outputs 4", "Sample Trigger 1", "Sample Trigger 2", "Sample Trigger 3", "Sample Trigger 4", "Sample Trigger 5", "Controller Update", "SW Protection Measured Signals Vo", "SW Protection Measured Signals Io", "SW Protection Measured Signals Vin", "SW Protection Measured Signals Iin", "SW Protection Upper Thresholds Vo", "SW Protection Upper Thresholds Io", "SW Protection Upper Thresholds Vin", "SW Protection Upper Thresholds Iin", "SW Protection Lower Thresholds Vo", "SW Protection Lower Thresholds Io", "SW Protection Lower Thresholds Vin", "SW Protection Lower Thresholds Iin", "SW Protection Fault Counters Vo", "SW Protection Fault Counters Io", "SW Protection Fault Counters Vin", "SW Protection Fault Counters Iin", "SW Protection Fault Comparators VoH", "SW Protection Fault Comparators VoL", "SW Protection Fault Comparators IoH", "SW Protection Fault Comparators IoL", "SW Protection Fault Comparators VinH", "SW Protection Fault Comparators VinL", "SW Protection Fault Comparators IinH", "SW Protection Fault Comparators IinL", "SW Protection Disable Latches Vo", "SW Protection Disable Latches Io", "SW Protection Disable Latches Vin", "SW Protection Disable Latches Iin", "SW Protection Enable Signal", "HW Protection Output Voltage Ref", "HW Protection Output Voltage In", "HW Protection Output Voltage VH", "HW Protection Output Voltage VL", "HW Protection Positive Output Current Ref", "HW Protection Positive Output Current In", "HW Protection Positive Output Current VH", "HW Protection Positive Output Current VL", "HW Protection Negative Output Current Ref", "HW Protection Negative Output Current In", "HW Protection Negative Output Current VH", "HW Protection Negative Output Current VL", "HW Protection Input Voltage Ref", "HW Protection Input Voltage In", "HW Protection Input Voltage VH", "HW Protection Input Voltage VL", "HW Protection Output Voltage 3", "HW Protection Positive Output Current 3", "HW Protection Negative Output Current 3", "HW Protection Input Voltage 3", "HW Protection Latch State", "HW Protection Reset State"],
               ["LL_HS_LS Dissipation 1", "LL_HS_LS Dissipation 2", "RL_HS_LS Dissipation 1", "RL_HS_LS Dissipation 2", "SR Dissipation 1", "SR Dissipation 2", "SC Switch Dissipation 1", "SC Switch Dissipation 2", "RCD Clamp Transistor Dissipation", "RCD Clamp Bodydiode Dissipation", "Transformer Rpri Copper Dissipation", "Transformer Rsec Copper Dissipation", "Transformer Core Dissipation", "Freewheeler Switch Dissipation 1", "Freewheeler Switch Dissipation 2", "LL TL", "RL TL", "SR TL", "SC TL", "RCD_TL", "Trafo TL", "DC Choke Dissipation", "IMS TL", "CT Sensor diode Dissipation", "FRW_TL", "CT Trafo Primary Dissipation", "CT Trafo Secondary Dissipation", "Choke RC Snubber Capacitor Dissipation", "Choke RC Snubber Resistance Dissipation", "Choke RC Snubber Rpar Dissipation", "RCD Clamp Capacitor Dissipation", "RCD Clamp Resistance Dissipation", "Freewheeler Blocking Cap Dissipation", "Freewheeler Resistor Dissipation", "Freewheeler Impedance Cap Dissipation", "Damping Resistor Dissipation", "LV Current Sensor Dissipation", "HV X-Caps 1 Dissipation", "HV X-Caps 2 Dissipation", "HV Current Sensor Dissipation", "Blocking Capacitor Dissipation", "Transformer Snubber Cap Dissipation", "Transformer Snubber Res Dissipation", "MOSFET RC Snubber Cap Dissipation", "MOSFET RC Snubber Res Dissipation", "HV Y-Caps Dissipation", "LV FullBridge Snubber Cap Dissipation", "LV FullBridge Snubber Res Dissipation", "HV Snubber Caps Dissipation", "Output Ceramic Capacitors Dissipation", "Output Electrolytic Capacitors Dissipation", "Output Y-Cap Dissipation", "HV Voltage Sensor Dissipation", "HV CMC Choke Dissipation", "LV Filter X-Cap 1 Dissipation", "LV Filter X-Cap 2 Dissipation", "LV Filter Elko-Cap Dissipation", "LV Filter Y-Cap Dissipation", "LV Filter DMC Dissipation", "LV Filter CMC Dissipation", "LV Filter Single Busbar Rb_Plus Dissipation", "LV Filter Single Busbar Rb_Minus Dissipation"],
               ["Target LV Voltage", "Target Load Power", "Target HV Voltage", "Measured Load Voltage L_F", "Measured Load Power L_F", "Measured Load Voltage L_B", "Measured Load Power L_B", "Measured HV Voltage", "Measured Load Current L_F", "Measured Load Current L_B", "Measured LV Output Voltage", "Measured LV Output Current", "Measured HV Current", "Measured Output Power", "Measured Input Power"],
[
    "CT Trafo Primary Current FFT",
    "CT Trafo Secondary Current FFT",
    "Choke RC Snubber Capacitor Current FFT",
    "Choke RC Snubber Resistance Current FFT",
    "Choke RC Snubber Par Res Current FFT",
    "RCD Clamp Capacitor Current FFT",
    "RCD Clamp Resistance Current FFT",
    "Freewheeler Blocking Cap Current FFT",
    "Freewheeler Resistor Current FFT",
    "Freewheeler Impedance Cap Current FFT",
    "Damping Resistor Current FFT",
    "LV Current Sensor Current FFT",
    "HV X-Caps 1 Current FFT",
    "HV X-Caps 2 Current FFT",
    "HV Current Sensor Current FFT",
    "Blocking Capacitor Current FFT",
    "Transformer Snubber Cap Current FFT",
    "Transformer Snubber Res Current FFT",
    "MOSFET RC Snubber Cap Current FFT",
    "MOSFET RC Snubber Res Current FFT",
    "HV Y-Caps Current FFT",
    "LV FullBridge Snubber Cap Current FFT",
    "LV FullBridge Snubber Res Current FFT",
    "HV Snubber Caps Current FFT",
    "Output Ceramic Capacitors Current FFT",
    "Output Electrolytic Capacitors Current FFT",
    "Output Y-Cap Current FFT",
    "HV Voltage Sensor Current FFT",
    "HV CMC Choke Current FFT",
    "LV Filter X-Cap 1 Current FFT",
    "LV Filter X-Cap 2 Current FFT",
    "LV Filter Elko-Cap Current FFT",
    "LV Filter Y-Cap Current FFT",
    "LV Filter DMC Current FFT",
    "LV Filter CMC Current FFT",
    "LV Filter Output Current RbPlus FFT",
    "LV Filter Output Current RbMinus FFT",
    "RCD Clamp Transistor Current FFT",
    "RCD Clamp Bodydiode Current FFT",
    "LV Rectifiers Current 1 FFT",
    "LV Rectifiers Current 2 FFT",
    "DC Choke Current FFT",
    "Freewheeler Switch Current 1 FFT",
    "Freewheeler Switch Current 2 FFT",
    "Short Circuit Current 1 FFT",
    "Short Circuit Current 2 FFT",
    "HV Left-Leg HS Current 1 FFT",
    "HV Left-Leg HS Current 2 FFT",
    "HV Right-Leg HS Current 1 FFT",
    "HV Right-Leg HS Current 2 FFT",
    "Transformer Primary Current FFT",
    "Transformer Secondary Current FFT",
    "Transformer Magnetizing Current FFT",
    "Pack Current FFT",
    "Relay Current Main FFT",
    "Relay Current DCDC FFT",
    "DC Link Current FFT",
    "KL30 Current FFT",
    "ENBN DCDC Current FFT",
    "ENBN Battery Current FFT",
    "LV Filter Input Current FFT",
    "LV Filter Output Current FFT",
    "CISPR Input Current FFT",
    "CISPR Output Current FFT",
    "Load L_F Current FFT",
    "Load L_B Current FFT",
    "CTRL Current FFT",
    "PECU Current FFT",
    "Rbox Current FFT"
],              
[
    "CT Trafo Primary Voltage FFT",
    "CT Trafo Secondary Voltage FFT",
    "Choke RC Snubber Voltage 1 FFT",
    "Choke RC Snubber Voltage 2 FFT",
    "Choke RC Snubber Voltage 3 FFT",
    "RCD Clamp Capacitor Voltage FFT",
    "RCD Clamp Resistance Voltage FFT",
    "Freewheeler Blocking Cap Voltage FFT",
    "Freewheeler Resistor Voltage FFT",
    "Freewheeler Impedance Cap Voltage FFT",
    "Damping Resistor Voltage FFT",
    "LV Current Sensor Voltage FFT",
    "HV X-Caps 1 Voltage FFT",
    "HV X-Caps 2 Voltage FFT",
    "HV Current Sensor Voltage FFT",
    "Blocking Capacitor Voltage FFT",
    "Transformer Snubber Voltage 1 FFT",
    "Transformer Snubber Voltage 2 FFT",
    "MOSFET RC Snubber Voltage 1 FFT",
    "MOSFET RC Snubber Voltage 2 FFT",
    "HV Y-Caps Voltage FFT",
    "LV FullBridge Snubber Voltage 1 FFT",
    "LV FullBridge Snubber Voltage 2 FFT",
    "HV Snubber Caps Voltage FFT",
    "Output Ceramic Capacitors Voltage FFT",
    "Output Electrolytic Capacitors Voltage FFT",
    "Output Y-Cap Voltage FFT",
    "HV Voltage Sensor Voltage FFT",
    "HV CMC Choke Voltage FFT",
    "LV Filter X-Cap 1 Voltage FFT",
    "LV Filter X-Cap 2 Voltage FFT",
    "LV Filter Elko-Cap Voltage FFT",
    "LV Filter Y-Cap Voltage FFT",
    "LV Filter DMC Voltage FFT",
    "LV Filter CMC Voltage FFT",
    "LV Filter Output Voltage 1 FFT",
    "LV Filter Output Voltage 2 FFT",
    "RCD Clamp Transistor Voltage FFT",
    "RCD Clamp Bodydiode Voltage FFT",
    "LV Rectifiers Voltage 1 FFT",
    "LV Rectifiers Voltage 2 FFT",
    "DC Choke Voltage FFT",
    "Freewheeler Switch Voltage 1 FFT",
    "Freewheeler Switch Voltage 2 FFT",
    "Short Circuit Voltage 1 FFT",
    "Short Circuit Voltage 2 FFT",
    "HV Left-Leg HS Voltage 1 FFT",
    "HV Left-Leg HS Voltage 2 FFT",
    "HV Right-Leg HS Voltage 1 FFT",
    "HV Right-Leg HS Voltage 2 FFT",
    "Transformer Primary Voltage FFT",
    "Transformer Secondary Voltage FFT",
    "Transformer Flux FFT",
    "Pack Voltage FFT",
    "Relay Voltage Main FFT",
    "Relay Voltage DCDC FFT",
    "DC Link Voltage FFT",
    "KL30 Voltage FFT",
    "ENBN DCDC Voltage FFT",
    "ENBN Battery Voltage FFT",
    "LV Filter Input Voltage FFT",
    "LV Filter Output Voltage 3 FFT",
    "CISPR Input Voltage FFT",
    "CISPR Output Voltage FFT",
    "Load L_F Voltage FFT",
    "Load L_B Voltage FFT",
    "CTRL Voltage FFT",
    "PECU Voltage FFT",
    "Rbox Voltage FFT"
],             ["CT Trafo Primary Current RMS", "CT Trafo Secondary Current RMS", "Choke RC Snubber Capacitor Current RMS", "Choke RC Snubber Resistance Current RMS", "Choke RC Snubber Par Res Current RMS", "RCD Clamp Capacitor Current RMS", "RCD Clamp Resistance Current RMS", "Freewheeler Blocking Cap Current RMS", "Freewheeler Resistor Current RMS", "Freewheeler Impedance Cap Current RMS", "Damping Resistor Current RMS", "LV Current Sensor Current RMS", "HV X-Caps 1 Current RMS", "HV X-Caps 2 Current RMS", "HV Current Sensor Current RMS", "Blocking Capacitor Current RMS", "Transformer Snubber Cap Current RMS", "Transformer Snubber Res Current RMS", "MOSFET RC Snubber Cap Current RMS", "MOSFET RC Snubber Res Current RMS", "HV Y-Caps Current RMS", "LV FullBridge Snubber Cap Current RMS", "LV FullBridge Snubber Res Current RMS", "HV Snubber Caps Current RMS", "Output Ceramic Capacitors Current RMS", "Output Electrolytic Capacitors Current RMS", "Output Y-Cap Current RMS", "HV Voltage Sensor Current RMS", "HV CMC Choke Current RMS", "LV Filter X-Cap 1 Current RMS", "LV Filter X-Cap 2 Current RMS", "LV Filter Elko-Cap Current RMS", "LV Filter Y-Cap Current RMS", "LV Filter DMC Current RMS", "LV Filter CMC Current RMS", "LV Filter Output Current RbPlus RMS", "LV Filter Output Current RbMinus RMS", "RCD Clamp Transistor Current RMS", "RCD Clamp Bodydiode Current RMS", "LV Rectifiers Current 1 RMS", "LV Rectifiers Current 2 RMS", "DC Choke Current RMS", "Freewheeler Switch Current 1 RMS", "Freewheeler Switch Current 2 RMS", "Short Circuit Current 1 RMS", "Short Circuit Current 2 RMS", "HV Left-Leg HS Current 1 RMS", "HV Left-Leg HS Current 2 RMS", "HV Right-Leg HS Current 1 RMS", "HV Right-Leg HS Current 2 RMS", "Transformer Primary Current RMS", "Transformer Secondary Current RMS", "Transformer Magnetizing Current RMS", "HV Left-Leg ON Current RMS", "HV Left-Leg OFF Current RMS", "HV Left-Leg Max Current1 RMS", "HV Left-Leg Max Current2 RMS", "HV Right-Leg ON Current RMS", "HV Right-Leg OFF Current RMS", "HV Right-Leg Max Current1 RMS", "HV Right-Leg Max Current2 RMS", "Pack Current RMS", "Relay Current Main RMS", "Relay Current DCDC RMS", "DC Link Current RMS", "KL30 Current RMS", "ENBN DCDC Current RMS", "ENBN Battery Current RMS", "LV Filter Input Current RMS", "LV Filter Output Current RMS", "CISPR Input Current RMS", "CISPR Output Current RMS", "Load L_F Current RMS", "Load L_B Current RMS", "CTRL Current RMS", "PECU Current RMS", "Rbox Current RMS"],
["CT Trafo Primary Current", "CT Trafo Secondary Current", "Choke RC Snubber Capacitor Current", "Choke RC Snubber Resistance Current", "Choke RC Snubber Par Res Current", "RCD Clamp Capacitor Current", "RCD Clamp Resistance Current", "Freewheeler Blocking Cap Current", "Freewheeler Resistor Current", "Freewheeler Impedance Cap Current", "Damping Resistor Current", "LV Current Sensor Current", "HV X-Caps 1 Current", "HV X-Caps 2 Current", "HV Current Sensor Current", "Blocking Capacitor Current", "Transformer Snubber Cap Current", "Transformer Snubber Res Current", "MOSFET RC Snubber Cap Current", "MOSFET RC Snubber Res Current", "HV Y-Caps Current", "LV FullBridge Snubber Cap Current", "LV FullBridge Snubber Res Current", "HV Snubber Caps Current", "Output Ceramic Capacitors Current", "Output Electrolytic Capacitors Current", "Output Y-Cap Current", "HV Voltage Sensor Current", "HV CMC Choke Current", "LV Filter X-Cap 1 Current", "LV Filter X-Cap 2 Current", "LV Filter Elko-Cap Current", "LV Filter Y-Cap Current", "LV Filter DMC Current", "LV Filter CMC Current", "LV Filter Output Current RbPlus", "LV Filter Output Current RbMinus", "RCD Clamp Transistor Current", "RCD Clamp Bodydiode Current", "LV Rectifiers Current 1", "LV Rectifiers Current 2", "DC Choke Current", "Freewheeler Switch Current 1", "Freewheeler Switch Current 2", "Short Circuit Current 1", "Short Circuit Current 2", "HV Left-Leg HS Current 1", "HV Left-Leg HS Current 2", "HV Right-Leg HS Current 1", "HV Right-Leg HS Current 2", "Transformer Primary Current", "Transformer Secondary Current", "Transformer Magnetizing Current", "HV Left-Leg ON Current", "HV Left-Leg OFF Current", "HV Left-Leg Max Current1", "HV Left-Leg Max Current2", "HV Right-Leg ON Current", "HV Right-Leg OFF Current", "HV Right-Leg Max Current1", "HV Right-Leg Max Current2", "Pack Current", "Relay Current Main", "Relay Current DCDC", "DC Link Current", "KL30 Current", "ENBN DCDC Current", "ENBN Battery Current", "LV Filter Input Current", "LV Filter Output Current", "CISPR Input Current", "CISPR Output Current", "Load L_F Current", "Load L_B Current", "CTRL Current", "PECU Current", "Rbox Current"],
["CT Trafo Primary Voltage", "CT Trafo Secondary Voltage", "Choke RC Snubber Voltage 1", "Choke RC Snubber Voltage 2", "Choke RC Snubber Voltage 3", "RCD Clamp Capacitor Voltage", "RCD Clamp Resistance Voltage", "Freewheeler Blocking Cap Voltage", "Freewheeler Resistor Voltage", "Freewheeler Impedance Cap Voltage", "Damping Resistor Voltage", "LV Current Sensor Voltage", "HV X-Caps 1 Voltage", "HV X-Caps 2 Voltage", "HV Current Sensor Voltage", "Blocking Capacitor Voltage", "Transformer Snubber Voltage 1", "Transformer Snubber Voltage 2", "MOSFET RC Snubber Voltage 1", "MOSFET RC Snubber Voltage 2", "HV Y-Caps Voltage", "LV FullBridge Snubber Voltage 1", "LV FullBridge Snubber Voltage 2", "HV Snubber Caps Voltage", "Output Ceramic Capacitors Voltage", "Output Electrolytic Capacitors Voltage", "Output Y-Cap Voltage", "HV Voltage Sensor Voltage", "HV CMC Choke Voltage", "LV Filter X-Cap 1 Voltage", "LV Filter X-Cap 2 Voltage", "LV Filter Elko-Cap Voltage", "LV Filter Y-Cap Voltage", "LV Filter DMC Voltage", "LV Filter CMC Voltage", "LV Filter Output Voltage 1", "LV Filter Output Voltage 2", "RCD Clamp Transistor Voltage", "RCD Clamp Bodydiode Voltage", "LV Rectifiers Voltage 1", "LV Rectifiers Voltage 2", "DC Choke Voltage", "Freewheeler Switch Voltage 1", "Freewheeler Switch Voltage 2", "Short Circuit Voltage 1", "Short Circuit Voltage 2", "HV Left-Leg HS Voltage 1", "HV Left-Leg HS Voltage 2", "HV Right-Leg HS Voltage 1", "HV Right-Leg HS Voltage 2", "Transformer Primary Voltage", "Transformer Secondary Voltage", "Transformer Flux", "Pack Voltage", "Relay Voltage Main", "Relay Voltage DCDC", "DC Link Voltage", "KL30 Voltage", "ENBN DCDC Voltage", "ENBN Battery Voltage", "LV Filter Input Voltage", "LV Filter Output Voltage 3", "CISPR Input Voltage", "CISPR Output Voltage", "Load L_F Voltage", "Load L_B Voltage", "CTRL Voltage", "PECU Voltage", "Rbox Voltage"],

               ["CT Trafo Primary Voltage RMS", "CT Trafo Secondary Voltage RMS", "Choke RC Snubber Voltage 1 RMS", "Choke RC Snubber Voltage 2 RMS", "Choke RC Snubber Voltage 3 RMS", "RCD Clamp Capacitor Voltage RMS", "RCD Clamp Resistance Voltage RMS", "Freewheeler Blocking Cap Voltage RMS", "Freewheeler Resistor Voltage RMS", "Freewheeler Impedance Cap Voltage RMS", "Damping Resistor Voltage RMS", "LV Current Sensor Voltage RMS", "HV X-Caps 1 Voltage RMS", "HV X-Caps 2 Voltage RMS", "HV Current Sensor Voltage RMS", "Blocking Capacitor Voltage RMS", "Transformer Snubber Voltage 1 RMS", "Transformer Snubber Voltage 2 RMS", "MOSFET RC Snubber Voltage 1 RMS", "MOSFET RC Snubber Voltage 2 RMS", "HV Y-Caps Voltage RMS", "LV FullBridge Snubber Voltage 1 RMS", "LV FullBridge Snubber Voltage 2 RMS", "HV Snubber Caps Voltage RMS", "Output Ceramic Capacitors Voltage RMS", "Output Electrolytic Capacitors Voltage RMS", "Output Y-Cap Voltage RMS", "HV Voltage Sensor Voltage RMS", "HV CMC Choke Voltage RMS", "LV Filter X-Cap 1 Voltage RMS", "LV Filter X-Cap 2 Voltage RMS", "LV Filter Elko-Cap Voltage RMS", "LV Filter Y-Cap Voltage RMS", "LV Filter DMC Voltage RMS", "LV Filter CMC Voltage RMS", "LV Filter Output Voltage 1 RMS", "LV Filter Output Voltage 2 RMS", "RCD Clamp Transistor Voltage RMS", "RCD Clamp Bodydiode Voltage RMS", "LV Rectifiers Voltage 1 RMS", "LV Rectifiers Voltage 2 RMS", "DC Choke Voltage RMS", "Freewheeler Switch Voltage 1 RMS", "Freewheeler Switch Voltage 2 RMS", "Short Circuit Voltage 1 RMS", "Short Circuit Voltage 2 RMS", "HV Left-Leg HS Voltage 1 RMS", "HV Left-Leg HS Voltage 2 RMS", "HV Right-Leg HS Voltage 1 RMS", "HV Right-Leg HS Voltage 2 RMS", "Transformer Primary Voltage RMS", "Transformer Secondary Voltage RMS", "Transformer Flux RMS", "Pack Voltage RMS", "Relay Voltage Main RMS", "Relay Voltage DCDC RMS", "DC Link Voltage RMS", "KL30 Voltage RMS", "ENBN DCDC Voltage RMS", "ENBN Battery Voltage RMS", "LV Filter Input Voltage RMS", "LV Filter Output Voltage 3 RMS", "CISPR Input Voltage RMS", "CISPR Output Voltage RMS", "Load L_F Voltage RMS", "Load L_B Voltage RMS", "CTRL Voltage RMS", "PECU Voltage RMS", "Rbox Voltage RMS"],
               ["HV FB Right Leg Temperature", "HV FB Left Leg Temperature", "Rectifier Temperature", "Short-Circuit Switch Temperature", "Active Clamp Switch Temperature", "Trafo Pri Winding Temperature", "Trafo Sec Winding Temperature", "Trafo Core Temperature", "Shunt Temperature", "Choke Winding Temperature", "Choke Core Temperature", "IMS Board Temperature", "Water Temperature", "HV FB Left Leg Rth", "HV FB Right Leg Rth", "Rectifier Rth", "Short-Circuit Switch Rth", "Active Clamp Switch Rth"],
               ["Single-Rail Total Dissipation", "Dual-Rail Total Dissipation", "Single-Rail Efficiency", "Dual-Rail Efficiency", "Single-Rail Efficiency Aux", "Dual-Rail Efficiency Aux", "Single-Rail Input Power", "Dual-Rail Input Power"]
               ]

fft_current = ["CT Trafo Primary Current", "CT Trafo Secondary Current", "Choke RC Snubber Capacitor Current", "Choke RC Snubber Resistance Current", "Choke RC Snubber Par Res Current", "RCD Clamp Capacitor Current", "RCD Clamp Resistance Current", "Freewheeler Blocking Cap Current", "Freewheeler Resistor Current", "Freewheeler Impedance Cap Current", "Damping Resistor Current", "LV Current Sensor Current", "HV X-Caps 1 Current", "HV X-Caps 2 Current", "HV Current Sensor Current", "Blocking Capacitor Current", "Transformer Snubber Cap Current", "Transformer Snubber Res Current", "MOSFET RC Snubber Cap Current", "MOSFET RC Snubber Res Current", "HV Y-Caps Current", "LV FullBridge Snubber Cap Current", "LV FullBridge Snubber Res Current", "HV Snubber Caps Current", "Output Ceramic Capacitors Current", "Output Electrolytic Capacitors Current", "Output Y-Cap Current", "HV Voltage Sensor Current", "HV CMC Choke Current", "LV Filter X-Cap 1 Current", "LV Filter X-Cap 2 Current", "LV Filter Elko-Cap Current", "LV Filter Y-Cap Current", "LV Filter DMC Current", "LV Filter CMC Current", "LV Filter Output Current RbPlus", "LV Filter Output Current RbMinus", "RCD Clamp Transistor Current", "RCD Clamp Bodydiode Current", "LV Rectifiers Current 1", "LV Rectifiers Current 2", "DC Choke Current", "Freewheeler Switch Current 1", "Freewheeler Switch Current 2", "Short Circuit Current 1", "Short Circuit Current 2", "HV Left-Leg HS Current 1", "HV Left-Leg HS Current 2", "HV Right-Leg HS Current 1", "HV Right-Leg HS Current 2", "Transformer Primary Current", "Transformer Secondary Current", "Transformer Magnetizing Current", "Pack Current", "Relay Current Main", "Relay Current DCDC", "DC Link Current", "KL30 Current", "ENBN DCDC Current", "ENBN Battery Current", "LV Filter Input Current", "LV Filter Output Current", "CISPR Input Current", "CISPR Output Current", "Load L_F Current", "Load L_B Current", "CTRL Current", "PECU Current", "Rbox Current"]
fft_voltage = ["CT Trafo Primary Voltage", "CT Trafo Secondary Voltage", "Choke RC Snubber Voltage 1", "Choke RC Snubber Voltage 2", "Choke RC Snubber Voltage 3", "RCD Clamp Capacitor Voltage", "RCD Clamp Resistance Voltage", "Freewheeler Blocking Cap Voltage", "Freewheeler Resistor Voltage", "Freewheeler Impedance Cap Voltage", "Damping Resistor Voltage", "LV Current Sensor Voltage", "HV X-Caps 1 Voltage", "HV X-Caps 2 Voltage", "HV Current Sensor Voltage", "Blocking Capacitor Voltage", "Transformer Snubber Voltage 1", "Transformer Snubber Voltage 2", "MOSFET RC Snubber Voltage 1", "MOSFET RC Snubber Voltage 2", "HV Y-Caps Voltage", "LV FullBridge Snubber Voltage 1", "LV FullBridge Snubber Voltage 2", "HV Snubber Caps Voltage", "Output Ceramic Capacitors Voltage", "Output Electrolytic Capacitors Voltage", "Output Y-Cap Voltage", "HV Voltage Sensor Voltage", "HV CMC Choke Voltage", "LV Filter X-Cap 1 Voltage", "LV Filter X-Cap 2 Voltage", "LV Filter Elko-Cap Voltage", "LV Filter Y-Cap Voltage", "LV Filter DMC Voltage", "LV Filter CMC Voltage", "LV Filter Output Voltage 1", "LV Filter Output Voltage 2", "RCD Clamp Transistor Voltage", "RCD Clamp Bodydiode Voltage", "LV Rectifiers Voltage 1", "LV Rectifiers Voltage 2", "DC Choke Voltage", "Freewheeler Switch Voltage 1", "Freewheeler Switch Voltage 2", "Short Circuit Voltage 1", "Short Circuit Voltage 2", "HV Left-Leg HS Voltage 1", "HV Left-Leg HS Voltage 2", "HV Right-Leg HS Voltage 1", "HV Right-Leg HS Voltage 2", "Transformer Primary Voltage", "Transformer Secondary Voltage", "Transformer Flux", "Pack Voltage", "Relay Voltage Main", "Relay Voltage DCDC", "DC Link Voltage", "KL30 Voltage", "ENBN DCDC Voltage", "ENBN Battery Voltage", "LV Filter Input Voltage", "LV Filter Output Voltage 3", "CISPR Input Voltage", "CISPR Output Voltage", "Load L_F Voltage", "Load L_B Voltage", "CTRL Voltage", "PECU Voltage", "Rbox Voltage"]


total_length = lambda all_headers: sum(len(sub) for sub in all_headers)
len_fft_current = len(fft_current)
len_fft_voltage = len(fft_voltage)

print("Total number of headers:", total_length(all_headers))
print("Number of FFT current headers:", len_fft_current)
print("Number of FFT voltage headers:", len_fft_voltage)
sub_lengths = lambda lst: [len(sub) for sub in lst]
print("Lengths of each sublist in all_headers:", sub_lengths(all_headers))


# import json
# jsonfile = r"D:\WORKSPACE\BJT-MODEL\assets\HEADER_FILES\FFT_Current.json"
# with open(jsonfile, "r", encoding="utf-8") as f:
#     data = json.load(f)

# # Append " FFT" to each element
# data = [item + " FFT" for item in data]

# with open(jsonfile, "w", encoding="utf-8") as f:
#     json.dump(data, f, indent=4)
